name: metafy_edge_detection_module
description: A new Flutter module project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  metafy_edge_detection:
    git:
      url: https://github.com/MaduraDiasTreinetic/metafy_edge_detection.git
      ref: main

  permission_handler: ^10.2.0
  path_provider: 2.0.10
  path: 1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.metafy_edge_detection_module
    iosBundleIdentifier: com.example.metafyEdgeDetectionModule
